### ISSUE TITLE
Using keywords as keys in designators

### ISSUE THREAD

**Issue by airballking** [cram-code/cram_core#28]
Currently, we use symbols from the package ```:desig-props``` as keys in designators. I often had problems with unregistered keys because I forgot to declare them as designator-properties in my package. 

I propose to use genuine keywords as keys in designators. This would remove the need for the package ```:desig-props``` and users of designators would not have to keep track of the keys which they use in the package definition.

Do you see any reason to not use genuine keywords for this?
@moesenle @gaya- @fairlight1337 @gheorghelisca @yazdani @bbrieber @mpomarlan

**Comment by fairlight1337** [comment]
It'll be a bit messy until every piece of code is adapted to that, but since its not  a structural change to how designators work, that shouldn't interrupt anything. I like the idea, had the same problems in the past (forgetting to declare keywords, having them in the wrong package, ...).

**Comment by moesenle** [comment]
Hi,

I like the idea, too.

Lorenz

**Comment by gaya-** [comment]
The old way of declaring designator properties can be kept as is for backwards compatibility.
I'll look into updating the location designator resolution to work with keywords though, I'll make a list of what needs to be changed and post it here.

**Comment by airballking** [comment]
I have been using genuine keywords in designators occassionally, and never experienced any functionality problem, i.e. getting, setting, comparing, etc. worked out of the box. The only thing that annoyed was the warning printed from the desig-props package for every operation that I was using an unregistered symbol in a designator.

So, I __guess__ it boils down to:
- [ ] extending the check for valid designator properties to accept any keyword
- [ ] put deprecation warnings into desig-props

**Comment by fairlight1337** [comment]
Totally in favor it that.

**Comment by gaya-** [comment]
Jan, do we want to refactor the location designators to have the props as keywords?

**Comment by fairlight1337** [comment]
Can't we just allow this type of keyword formulation and leave the location designators as they are for now (`at`, `pose`, `on`, ...)? We can change predicates as appropriate, bit by bit.

I'm just saying, because at the moment everything seems to work fine and refactoring tends to break stuff. I can't afford refactoring large parts of the code base right now.

But in general, if we allow this for action/object designators, location designators shouldn't be much different, no?

**Comment by gaya-** [comment]
Ok.

Shouldn't be different, locations are the biggest and the hardest to refactor, hence me asking about locations in particular.

**Comment by airballking** [comment]
I am in favor of introducing this feature, and, in time, we can refactor the different packages. 

However, sometimes I get the impression that there is never any time to refactor. I think sometimes we just have to bite the bullet if it means improving the project. And this seems like a wide-spread but fairly mechanic tweak to me.

**Comment by gaya-** [comment]
I was referring to refactoring the existing designator descriptions to
comply with the keyword format, which will affect all the packages that we
have, core, highlevel, physics, pr2, maybe bridge, and the demos, which is,
of course, more than

> extending the check for valid designator properties to accept any keyword
> put deprecation warnings into desig-props

I'll try to do that in my fork and show the results to Jan, maybe it works
out.

**Comment by gaya-** [comment]
Oh, I misunderstood you, I guess you were referring to the same as well.

**Comment by fairlight1337** [comment]
Hey,

I didn't say we shouldn't do it. Let's just not do all of it at the same time ;). Because that's gonna halt everything CRAM related until everything is ready after refactoring. Hence the proposition to push back the core functionalities of location designators until the rest is in a stable state again.

**Comment by gaya-** [comment]
Solved in https://github.com/cram2/cram_core/commit/56d92f498c5034d535791e70fee010d69b4ac8fb and other related ones.
